# Generated by Django 4.0.6 on 2022-08-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('profile', 'friend_profile')},
        ),
    ]
